server:
  port: 8092
spring:
  application:
    name: BE_TTCS
  datasource:
    url: jdbc:mysql://localhost:3306/basse_e
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springdoc: DEBUG
    org.springdoc.api: DEBUG
